baseURL = "http://example.org/"
languageCode = "en-us"
title = "Data Narrator Sandbox"
ignoreFiles = [ "\\.Rmd$", "_files$", "_cache$", "index\\.html", "renv", 
		"\\.Rprofile$", "\\.Renviron$", "renv.lock"]

[permalinks]
  blog = "/:year/:month/:day/:slug/"

[taxonomies]
  tag = "tags"


